name: Execute and report a JQF performance evaluation campaign
on:
  workflow_dispatch:
    inputs:
      trials:
        description: Number of trials to conduct of each fuzzing target
        required: false
        default: 5
        type: number
      duration:
        description: Duration of each fuzzing campaign, e.g. 5m, 24h
        required: false
        default: 5m
        type: string
jobs:
  clone_cloudlab_repo:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: aoli-al/cloudlab
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: master
